name: Docker test

on:
  workflow_dispatch:
  push:
    # trigger only on main branch
    branches:
      - main
    # trigger only on changes to the following files
    paths:
      - "grpc-web-proxy/conf/**"
      - "grpc-web-proxy/start.sh"
      - "Dockerfile"
      - ".github/workflows/test-docker.yaml"
  pull_request:
    # trigger only on main branch
    branches:
      - main
    # trigger only on changes to the following files
    paths:
      - "grpc-web-proxy/conf/**"
      - "grpc-web-proxy/start.sh"
      - "Dockerfile"
      - ".github/workflows/docker-build.yaml"

jobs:
  test-docker:
    name: Run tests inside Docker container
    runs-on: ubuntu-latest
    steps:
      - # get repository code
        name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build the image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: grpc-web-proxy:latest
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, mode=max, scope=${{ github.workflow }}
